import { createTamagui, createTokens, createFont } from 'tamagui';

const colors = {
  primary: '#EB6522',
  primaryDark: '#CC4400',
  primaryLight: '#FFE0CC',
  star: '#fbbf24',
  success: '#2D6A4F',
  warning: '#E9C46A',
  accent: '#CC0000',

  light_bg: '#ffffff',
  light_bgAlt: '#fafafa',
  light_surface: '#f4f4f5',
  light_surfaceElevated: '#ffffff',
  light_border: '#f4f4f5',
  light_hairline: '#e4e4e7',
  light_text: '#18181b',
  light_textMuted: '#71717a',
  light_textFaint: '#a1a1aa',
  light_onPrimary: '#ffffff',
  light_overlay: 'rgba(24,24,27,0.4)',

  dark_bg: '#09090b',
  dark_bgAlt: '#0b0c0e',
  dark_surface: '#18181b',
  dark_surfaceElevated: '#27272a',
  dark_border: '#27272a',
  dark_hairline: '#3f3f46',
  dark_text: '#ffffff',
  dark_textMuted: '#a1a1aa',
  dark_textFaint: '#71717a',
  dark_onPrimary: '#ffffff',
  dark_overlay: 'rgba(9,9,11,0.6)',
};

const tokens = createTokens({
  size: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  space: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 999,
  },
  zIndex: {
    hide: -1,
    base: 0,
    low: 10,
    medium: 100,
    high: 1000,
    overlay: 2000,
    modal: 3000,
    toast: 4000,
    tooltip: 5000,
  },
  color: colors,
});

const headingFont = createFont({
  family: 'System',
  size: {
    1: 13,
    2: 15,
    3: 17,
    4: 20,
    5: 23,
    6: 26,
    7: 32,
    8: 40,
    9: 48,
  },
  weight: {
    1: '400',
    2: '500',
    3: '600',
    4: '700',
    5: '800',
    6: '900',
  },
  lineHeight: {
    1: 18,
    2: 20,
    3: 24,
    4: 28,
    5: 32,
    6: 34,
    7: 40,
    8: 48,
    9: 56,
  },
  letterSpacing: {
    1: 0,
    2: -0.4,
    3: -0.8,
  },
});

const bodyFont = createFont({
  family: 'System',
  size: {
    1: 11,
    2: 12,
    3: 13,
    4: 14,
    5: 15,
    6: 16,
    7: 18,
    8: 20,
    9: 24,
  },
  weight: {
    1: '400',
    2: '500',
    3: '600',
    4: '700',
  },
  lineHeight: {
    1: 16,
    2: 17,
    3: 18,
    4: 20,
    5: 22,
    6: 24,
    7: 26,
    8: 28,
    9: 32,
  },
  letterSpacing: {
    1: 0,
    2: 0.2,
  },
});

const config = createTamagui({
  defaultTheme: 'light',
  tokens,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes: {
    light: {
      bg: colors.light_bg,
      bgAlt: colors.light_bgAlt,
      surface: colors.light_surface,
      surfaceElevated: colors.light_surfaceElevated,
      border: colors.light_border,
      hairline: colors.light_hairline,
      text: colors.light_text,
      textMuted: colors.light_textMuted,
      textFaint: colors.light_textFaint,
      onPrimary: colors.light_onPrimary,
      overlay: colors.light_overlay,
      primary: colors.primary,
      primaryDark: colors.primaryDark,
      primaryLight: colors.primaryLight,
      star: colors.star,
      success: colors.success,
      warning: colors.warning,
      accent: colors.accent,
      background: colors.light_bg,
      color: colors.light_text,
      placeholderColor: colors.light_textFaint,
    },
    dark: {
      bg: colors.dark_bg,
      bgAlt: colors.dark_bgAlt,
      surface: colors.dark_surface,
      surfaceElevated: colors.dark_surfaceElevated,
      border: colors.dark_border,
      hairline: colors.dark_hairline,
      text: colors.dark_text,
      textMuted: colors.dark_textMuted,
      textFaint: colors.dark_textFaint,
      onPrimary: colors.dark_onPrimary,
      overlay: colors.dark_overlay,
      primary: colors.primary,
      primaryDark: colors.primaryDark,
      primaryLight: colors.primaryLight,
      star: colors.star,
      success: colors.success,
      warning: colors.warning,
      accent: colors.accent,
      background: colors.dark_bg,
      color: colors.dark_text,
      placeholderColor: colors.dark_textFaint,
    },
  },
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 661 },
    gtSm: { minWidth: 801 },
    gtMd: { minWidth: 1021 },
    gtLg: { minWidth: 1281 },
    gtXl: { minWidth: 1421 },
    short: { maxHeight: 820 },
    tall: { minHeight: 821 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
  shorthands: {
    bg: 'backgroundColor',
    bgAlt: 'backgroundColor',
    surface: 'backgroundColor',
    surfaceElevated: 'backgroundColor',
    border: 'borderColor',
    hairline: 'borderColor',
    text: 'color',
    textMuted: 'color',
    textFaint: 'color',
    onPrimary: 'color',
    overlay: 'backgroundColor',
    primary: 'backgroundColor',
    primaryDark: 'backgroundColor',
    primaryLight: 'backgroundColor',
    star: 'color',
    success: 'backgroundColor',
    warning: 'backgroundColor',
    accent: 'backgroundColor',
    p: 'padding',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    m: 'margin',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    r: 'borderRadius',
    rt: 'borderTopRadius',
    rb: 'borderBottomRadius',
    rs: 'borderStartRadius',
    re: 'borderEndRadius',
    br: 'borderRadius',
    btr: 'borderTopRightRadius',
    btl: 'borderTopLeftRadius',
    bbr: 'borderBottomRightRadius',
    bbl: 'borderBottomLeftRadius',
    z: 'zIndex',
    fs: 'fontSize',
    fw: 'fontWeight',
    lh: 'lineHeight',
    ls: 'letterSpacing',
    ta: 'textAlign',
    ff: 'fontFamily',
    op: 'opacity',
    abs: 'position',
    absTL: 'absoluteTopLeft',
    absTR: 'absoluteTopRight',
    absBL: 'absoluteBottomLeft',
    absBR: 'absoluteBottomRight',
    inset: 'inset',
    insetX: 'insetHorizontal',
    insetY: 'insetVertical',
    gap: 'gap',
    rowGap: 'rowGap',
    columnGap: 'columnGap',
    flex: 'flex',
    flexDir: 'flexDirection',
    flexWrap: 'flexWrap',
    align: 'alignItems',
    justify: 'justifyContent',
    self: 'alignSelf',
    grow: 'flexGrow',
    shrink: 'flexShrink',
    basis: 'flexBasis',
    w: 'width',
    h: 'height',
    minW: 'minWidth',
    maxW: 'maxWidth',
    minH: 'minHeight',
    maxH: 'maxHeight',
    size: 'size',
    sq: 'size',
  },
});

export type AppConfig = typeof config;

declare module 'tamagui' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;