import { createTamagui, createTokens, createFont } from 'tamagui';
import { brand, neutral, light, dark } from './src/theme/colors';
import { spacing as spacingScale, radius as radiusScale } from './src/theme/spacing';

// ============================================================================
// TAMAGUI TOKENS — imported from src/theme/ (single source of truth)
// ============================================================================

const tamaguiColors = {
  // Brand
  brandOrange: brand.orange,
  brandOrangeStrong: brand.orangeStrong,
  brandOrangeSoft: brand.orangeSoft,
  brandOrangeBright: brand.orangeBright,
  brandOrangeDeep: brand.orangeDeep,
  brandStar: brand.star,
  brandStarDark: brand.starDark,
  brandStarSoft: brand.starSoft,
  brandSuccess: brand.success,
  brandSuccessSoft: brand.successSoft,
  brandSuccessStrong: brand.successStrong,
  brandWarning: brand.warning,
  brandWarningSoft: brand.warningSoft,
  brandWarningStrong: brand.warningStrong,
  brandError: brand.error,
  brandErrorSoft: brand.errorSoft,
  brandErrorStrong: brand.errorStrong,

  // Light semantic
  lightBg: light.background.primary,
  lightBgAlt: light.background.secondary,
  lightSurface: light.surface.primary,
  lightSurfaceElevated: light.surface.elevated,
  lightSurfaceSunken: light.surface.sunken,
  lightBorderSubtle: light.border.subtle,
  lightBorderDefault: light.border.default,
  lightBorderStrong: light.border.strong,
  lightTextPrimary: light.text.primary,
  lightTextSecondary: light.text.secondary,
  lightTextTertiary: light.text.tertiary,
  lightTextDisabled: light.text.disabled,
  lightTextInverse: light.text.inverse,
  lightTextBrand: light.text.brand,
  lightActionPrimaryBg: light.action.primary.background,
  lightActionPrimaryFg: light.action.primary.foreground,
  lightActionPrimaryPressed: light.action.primary.pressed,
  lightActionSecondaryBg: light.action.secondary.background,
  lightActionSecondaryFg: light.action.secondary.foreground,
  lightActionSecondaryBorder: light.action.secondary.border,
  lightOverlay: light.overlay,

  // Dark semantic
  darkBg: dark.background.primary,
  darkBgAlt: dark.background.secondary,
  darkSurface: dark.surface.primary,
  darkSurfaceElevated: dark.surface.elevated,
  darkSurfaceSunken: dark.surface.sunken,
  darkBorderSubtle: dark.border.subtle,
  darkBorderDefault: dark.border.default,
  darkBorderStrong: dark.border.strong,
  darkTextPrimary: dark.text.primary,
  darkTextSecondary: dark.text.secondary,
  darkTextTertiary: dark.text.tertiary,
  darkTextDisabled: dark.text.disabled,
  darkTextInverse: dark.text.inverse,
  darkTextBrand: dark.text.brand,
  darkActionPrimaryBg: dark.action.primary.background,
  darkActionPrimaryFg: dark.action.primary.foreground,
  darkActionPrimaryPressed: dark.action.primary.pressed,
  darkActionSecondaryBg: dark.action.secondary.background,
  darkActionSecondaryFg: dark.action.secondary.foreground,
  darkActionSecondaryBorder: dark.action.secondary.border,
  darkOverlay: dark.overlay,

  // Status (shared)
  statusSuccessPrimary: brand.success,
  statusSuccessSoft: brand.successSoft,
  statusWarningPrimary: brand.warning,
  statusWarningSoft: brand.warningSoft,
  statusErrorPrimary: brand.error,
  statusErrorSoft: brand.errorSoft,
  statusStarPrimary: brand.star,
  statusStarSoft: brand.starSoft,

  // Legacy aliases
  primary: brand.orange,
  primaryDark: brand.orangeStrong,
  primaryLight: brand.orangeSoft,
  star: brand.star,
  success: brand.success,
  warning: brand.warning,
  accent: brand.accent,

  light_bg: light.background.primary,
  light_bgAlt: light.background.secondary,
  light_surface: light.surface.primary,
  light_surfaceElevated: light.surface.elevated,
  light_border: light.border.default,
  light_hairline: light.border.subtle,
  light_text: light.text.primary,
  light_textMuted: light.text.secondary,
  light_textFaint: light.text.tertiary,
  light_onPrimary: light.text.inverse,
  light_overlay: light.overlay,

  dark_bg: dark.background.primary,
  dark_bgAlt: dark.background.secondary,
  dark_surface: dark.surface.primary,
  dark_surfaceElevated: dark.surface.elevated,
  dark_border: dark.border.default,
  dark_hairline: dark.border.subtle,
  dark_text: dark.text.primary,
  dark_textMuted: dark.text.secondary,
  dark_textFaint: dark.text.tertiary,
  dark_onPrimary: dark.text.inverse,
  dark_overlay: dark.overlay,
};

const tokens = createTokens({
  size: {
    xxs: spacingScale.xxs,
    xs: spacingScale.xs,
    sm: spacingScale.sm,
    md: spacingScale.md,
    true: spacingScale.md,
    lg: spacingScale.lg,
    xl: spacingScale.xl,
    xxl: spacingScale.xxl,
    xxxl: spacingScale.xxxl,
    huge: spacingScale.huge,
    massive: spacingScale.massive,
    extreme: spacingScale.extreme,
  },
  space: {
    xxs: spacingScale.xxs,
    xs: spacingScale.xs,
    sm: spacingScale.sm,
    md: spacingScale.md,
    true: spacingScale.md,
    lg: spacingScale.lg,
    xl: spacingScale.xl,
    xxl: spacingScale.xxl,
    xxxl: spacingScale.xxxl,
    huge: spacingScale.huge,
    massive: spacingScale.massive,
    extreme: spacingScale.extreme,
  },
  radius: {
    xs: radiusScale.xs,
    sm: radiusScale.sm,
    md: radiusScale.md,
    lg: radiusScale.lg,
    xl: radiusScale.xl,
    xxl: radiusScale.xxl,
    pill: radiusScale.pill,
    full: radiusScale.full,
  },
  zIndex: {
    xxs: -1,
    xs: 0,
    sm: 10,
    md: 100,
    true: 100,
    lg: 1000,
    xl: 2000,
    xxl: 5000,
  },
  color: tamaguiColors,
});

// Font configuration
const headingFont = createFont({
  family: 'System',
  size: {
    1: 11,
    2: 12,
    3: 14,
    4: 16,
    5: 17,
    6: 17,
    7: 20,
    8: 24,
    9: 28,
  },
  weight: {
    1: '400',
    2: '500',
    3: '600',
    4: '700',
    5: '800',
    6: '900',
  },
  lineHeight: {
    1: 14,
    2: 16,
    3: 22,
    4: 24,
    5: 26,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
  },
  letterSpacing: {
    1: 0,
    2: 0,
    3: 0,
    4: 0,
    5: -0.4,
    6: -0.4,
  },
});

const bodyFont = createFont({
  family: 'System',
  size: {
    1: 11,
    2: 12,
    3: 14,
    4: 16,
    5: 17,
    6: 17,
    7: 20,
    8: 24,
    9: 28,
  },
  weight: {
    1: '400',
    2: '500',
    3: '600',
    4: '700',
  },
  lineHeight: {
    1: 14,
    2: 16,
    3: 22,
    4: 24,
    5: 26,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
  },
  letterSpacing: {
    1: 0,
    2: 0.2,
  },
});

/**
 * Tamagui config — minimal, only for primitives (Text in EmptyState, etc.)
 * All app styling flows through the custom ThemeContext (src/theme/).
 * Colors and spacing imported from src/theme/ — single source of truth.
 */
const config = createTamagui({
  defaultTheme: 'light',
  tokens,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes: {
    light: {
      background: light.background.primary,
      color: light.text.primary,
      placeholderColor: light.text.tertiary,
    },
    dark: {
      background: dark.background.primary,
      color: dark.text.primary,
      placeholderColor: dark.text.tertiary,
    },
  },
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 661 },
    gtSm: { minWidth: 801 },
    gtMd: { minWidth: 1021 },
    gtLg: { minWidth: 1281 },
    gtXl: { minWidth: 1421 },
    short: { maxHeight: 820 },
    tall: { minHeight: 821 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
  shorthands: {
    bg: 'backgroundColor',
    bgAlt: 'backgroundColor',
    surface: 'backgroundColor',
    surfaceElevated: 'backgroundColor',
    border: 'borderColor',
    hairline: 'borderColor',
    text: 'color',
    textMuted: 'color',
    textFaint: 'color',
    onPrimary: 'color',
    overlay: 'backgroundColor',
    primary: 'backgroundColor',
    primaryDark: 'backgroundColor',
    primaryLight: 'backgroundColor',
    star: 'color',
    success: 'backgroundColor',
    warning: 'backgroundColor',
    accent: 'backgroundColor',
    p: 'padding',
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    m: 'margin',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    r: 'borderRadius',
    rt: 'borderTopRadius',
    rb: 'borderBottomRadius',
    rs: 'borderStartRadius',
    re: 'borderEndRadius',
    br: 'borderRadius',
    btr: 'borderTopRightRadius',
    btl: 'borderTopLeftRadius',
    bbr: 'borderBottomRightRadius',
    bbl: 'borderBottomLeftRadius',
    z: 'zIndex',
    fs: 'fontSize',
    fw: 'fontWeight',
    lh: 'lineHeight',
    ls: 'letterSpacing',
    ta: 'textAlign',
    ff: 'fontFamily',
    op: 'opacity',
    abs: 'position',
    absTL: 'absoluteTopLeft',
    absTR: 'absoluteTopRight',
    absBL: 'absoluteBottomLeft',
    absBR: 'absoluteBottomRight',
    inset: 'inset',
    insetX: 'insetHorizontal',
    insetY: 'insetVertical',
    gap: 'gap',
    rowGap: 'rowGap',
    columnGap: 'columnGap',
    flex: 'flex',
    flexDir: 'flexDirection',
    flexWrap: 'flexWrap',
    align: 'alignItems',
    justify: 'justifyContent',
    self: 'alignSelf',
    grow: 'flexGrow',
    shrink: 'flexShrink',
    basis: 'flexBasis',
    w: 'width',
    h: 'height',
    minW: 'minWidth',
    maxW: 'maxWidth',
    minH: 'minHeight',
    maxH: 'maxHeight',
    size: 'size',
    sq: 'size',
  },
});

export type AppConfig = typeof config;

declare module 'tamagui' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;
